# Generated by Django 3.2.3 on 2021-06-08 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_orderupdate_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='update_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
