# Generated by Django 3.2.3 on 2021-06-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210608_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
